### ISSUE TITLE
How to reproduce the results

### ISSUE THREAD

**Issue by nick89216kuo** [CHeggan/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark#13]
Hello, researcher!

Recently, I have been attempting to reproduce my previous experimental results but encountered some issues. I would like to seek advice regarding the matter of seed.

My understanding is that setting the seed to the same value should yield the same accuracy in training for two different runs. However, this is not the case for me. I made some modifications to the code in BaseLooper.py to ensure that training uses the same seed, as shown below:

seed = np.random.randint(low=0, high=1000)
set_seed(seed)
params['base']['seed'] = seed

Changed to:

seed = params['base']['seed']
set_seed(seed)

I would like to ask if my understanding of the seed is incorrect?
Thanks you!

**Comment by CHeggan** [comment]
Hi there, 

Your understanding of the seed is indeed correct and this does seem like weird behaviour. 

So for context, the set_seed function as used just manually sets all the important packages seed (it was just nice to have it wrapped up in a single call). This includes things like torch, NumPy and base python random. 

I would guess that the following could be one possible issue:
 - Packages are not the same versions/the environment is not configured the same as was used when the original repo was created. This could be causing some unexpected behaviour where seeds are not being set properly due to, for example packages having updated methods for seed setting. I am aware of a currently open issue where the environment file for the repo is not functioning properly and so if to get around this, a manual setup was used, I would suggest making sure that all the packages included in the set_seed function are as expected from the existing (albeit auto-install broken) environment file. Even if all of the, in theory, packages are correct versions it is still possible that other packages with different versions have influence (although this would be a hard issue to solve if the case)

Using the set_seed function in a fresh script and experimenting with the packages included within its bounds, i.e. torch, NumPy etc, may also help locate this issue more efficiently. 

Hope these insights help!

Best,
Calum
