### ISSUE TITLE
About the accuracy of 5-way 5-shot

### ISSUE THREAD

**Issue by nick89216kuo** [CHeggan/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark#18]
Researcher, hello!
Recently, I have been conducting experiments on 5-way 5-shot learning. I used the example code for ESC-50, and I modified the configuration file by setting k_shot to 5, while keeping the rest of the settings the same. The accuracy is shown in the following figure.

![image](https://github.com/CHeggan/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark/assets/141639925/7751bcb6-0461-450a-b2dc-8c7826a523db)

The accuracy of 97% differs from the data in other papers. I would like to inquire whether there is a difference with the results from you, the researcher, or if there are any aspects I should pay attention to. Thank you.

**Comment by CHeggan** [comment]
Hi there, 

I am not sure which other papers you mean, can you point to them if possible? The results below were never published due to space limitations at the conference MetaAudio went to. 

![image](https://github.com/CHeggan/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark/assets/38021095/868c0be6-d233-4389-9f5b-eb5f9c047a5f)

By the looks of it, ~97% performance on 5-way 5-shot meta-curvature makes sense and aligns with the results shown.

Hope this helps!

Cheers,
Calum
