### ISSUE TITLE
Unable to run example for MAML_ESC

### ISSUE THREAD

**Issue by racheltlw** [CHeggan/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark#3]
Hi! Great repo! 

I'm trying to run your example and was able to complete Step 1 'Getting and Formatting the Data' with 1 change: 
In line 45 of [to_spec.py ](https://github.com/CHeggan/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark/blob/quick_changes/Dataset%20Processing/to_spec.py) I had to change '160000' to '80000' since the audio data had a shape of (80000,). 

However on step 2, I followed the instruction and ran BaseLooper.py, however am getting the following error 'IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)', which is an issue in [stat_recorder_class.py](https://github.com/CHeggan/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark/blob/main/Examples/MAML_ESC/dataset_/stat_recorder_class.py), a portion of the function below, when calculating the mean across dimensions (0,1,2): 

```
 def update(self, data):
        """
        data: ndarray, shape (nobservations, ndimensions)
        """
        # initialize stats and dimensions on first batch
        if self.nobservations == 0:
            print('SHAPE', data.shape) # I printed the shape, it is 'SHAPE torch.Size([64000, 157])'
            self.mean = data.mean(
                dim=self.red_dims, keepdim=True)
            self.std  = data.std (dim=self.red_dims,keepdim=True)
            self.nobservations = data.shape[0]
            self.ndimensions   = data.shape[1]
```
Here are the params I am passing in from the yaml file (no changes made except for the task type and data path. 

```
{'base': {'n_way': 5, 'k_shot': 1, 'q_queries': 1, 'cuda': 0, 'num_repeats': 1, 'task_type': 'MAML_ESC_TRIAL_6Nov22Hybrid_global_1_runs', 'seed': 927}, 'models': ['Hybrid'], 'hyper': {'inner_train_steps': 8, 'inner_val_steps': 8, 'inner_lr': 0.4, 'meta_lr': 0.001, 'min_lr': 0.001, 'T_max': 1}, 'training': {'epochs': 200, 'episodes_per_epoch': 10, 'train_batch_size': 50, 'val_tasks': 200, 'test_tasks': 1000, 'trans_batch': False, 'eval_spacing': 10, 'break_threshold': 500, 'warm_up': 100000, 'num_workers': 4}, 'data': {'variable': False, 'name': 'ESC', 'norm': 'global', 'type': 'variable_spec', 'fixed': True, 'fixed_path': 'dataset_/splits/ESC_paper_splits.npy', 'data_path': 'C:/Users/Rachel Tan/Documents/GitHub/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark/ESC-50-master/ESC_spec'}, 'split': {'train': 0.7, 'val': 0.1, 'test': 0.2}} 
```

Any idea what could be the issue or how to make debug the example?

**Comment by CHeggan** [comment]
Hi there, 

Apologies for the very large delay on replying to this issue. 

You may have already solved this issue, but incase you haven't, here are some ideas:

- So the issue l think will be something to do with whether the input to the normalisation class is a spectrogram(2d or 3d batched) or whether it is raw audio (1d or 2d batched). Effectively it is probably due to the function/class thibning the input is wrong

- For debugging I would recommend removing the options to the function and fixing it for your use case, i.e fix the class to work for a 2d or 3d inout. It isn't an ideal solution but would work as a temporary fix if you are set on using either raw audio or spectrograms moving forward

Apologies I can't give a more accurate answer at the moment, but hopefully these ideas help a bit. 

I will have a look at updating the codebase to remove this issue or at least make the issues better described in output.

Cheers,
Calum

**Comment by CHeggan** [comment]
So looking at the update function again, I think it may be that the defined red_dims may be an incorrect size.

 If the input data is only 2d, and red_dims indexes up to a dimension 2 i.e you mentioned (0,1,2), then it may trying to iterate over the batch hut its not there. 

It could be worth checking:
- That the input to the function contains the batch dimension, if only using 1 sample you may have to use the unsqueeze torch function on inputs 
- The size of rem_dims compared to the input

Cheers,
Calum
